spring.application.name=capital-cruise-backend

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

server.port=8080

capital-cruise.exchange-rate.provider=${EXCHANGE_RATE_PROVIDER:EXCHANGERATE_API_OPEN}
capital-cruise.exchange-rate.open-api-base-url=${EXCHANGE_RATE_OPEN_API_BASE_URL:https://open.er-api.com/v6/latest}
capital-cruise.exchange-rate.cache-ttl-minutes=${EXCHANGE_RATE_CACHE_TTL_MINUTES:720}
capital-cruise.exchange-rate.fallback-usd-pen=${EXCHANGE_RATE_FALLBACK_USD_PEN:3.7500}
capital-cruise.exchange-rate.allow-stale-on-provider-error=${EXCHANGE_RATE_ALLOW_STALE_ON_PROVIDER_ERROR:true}
