create table roles (
    id bigint generated by default as identity primary key,
    name varchar(30) not null unique
);

create table users (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    username varchar(80) not null unique,
    email varchar(120) not null unique,
    password_hash varchar(120) not null,
    is_active boolean not null,
    last_login_at timestamp with time zone null
);

create table user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    constraint fk_user_roles_user foreign key (user_id) references users (id) on delete cascade,
    constraint fk_user_roles_role foreign key (role_id) references roles (id) on delete cascade
);

create table refresh_tokens (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    token_hash varchar(128) not null unique,
    expires_at timestamp with time zone not null,
    revoked_at timestamp with time zone null,
    created_at timestamp with time zone not null,
    constraint fk_refresh_tokens_user foreign key (user_id) references users (id) on delete cascade
);
