create table roles (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    name varchar(30) not null unique
);

create table users (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    username varchar(80) not null unique,
    password_hash varchar(120) not null
);

create table user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    constraint fk_user_roles_user foreign key (user_id) references users (id) on delete cascade,
    constraint fk_user_roles_role foreign key (role_id) references roles (id) on delete cascade
);

create table profiles (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    first_name varchar(80) not null,
    last_name varchar(80) not null,
    email varchar(120) not null unique,
    document_number varchar(8),
    user_id bigint,
    constraint fk_profiles_user foreign key (user_id) references users (id) on delete set null
);
