create table profiles (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    first_name varchar(80) not null,
    last_name varchar(80) not null,
    email varchar(120) not null unique,
    document_number varchar(8),
    user_id bigint,
    constraint fk_profiles_user foreign key (user_id) references users (id) on delete set null
);
