create table clients (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    first_name varchar(80) not null,
    last_name varchar(80) not null,
    document_type varchar(20) not null,
    document_number varchar(40) not null unique,
    email varchar(120),
    phone varchar(30),
    address varchar(255),
    monthly_income numeric(19,2) not null,
    notes varchar(1000)
);
