create table vehicles (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    brand varchar(80) not null,
    model varchar(80) not null,
    vehicle_year integer not null,
    vehicle_type varchar(20) not null,
    commercial_price numeric(19,2) not null,
    currency varchar(10) not null,
    description varchar(1000),
    image_url varchar(500)
);
