create table exchange_rates (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    base_currency varchar(3) not null,
    quote_currency varchar(3) not null,
    rate numeric(19,4) not null,
    source varchar(50) not null,
    quoted_at timestamp with time zone not null
);

create index idx_exchange_rates_pair_quoted_at
    on exchange_rates (base_currency, quote_currency, quoted_at desc);
