create table loan_operations (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    user_id bigint not null,
    client_id bigint not null,
    vehicle_id bigint not null,
    status varchar(20) not null,
    operation_currency varchar(3) not null,
    vehicle_price numeric(19,2) not null,
    down_payment_amount numeric(19,2),
    down_payment_percent numeric(19,4),
    term_months integer not null,
    start_date date not null,
    rate_type varchar(20) not null,
    rate_value numeric(19,4) not null,
    rate_period varchar(20) not null,
    capitalization_frequency varchar(20),
    grace_type varchar(20) not null,
    grace_periods integer not null,
    balloon_amount numeric(19,2),
    balloon_percent numeric(19,4),
    exchange_rate_mode varchar(20) not null,
    exchange_rate_value numeric(19,4),
    discount_rate numeric(19,4) not null,
    client_snapshot_name varchar(200) not null,
    client_snapshot_document_type varchar(20) not null,
    client_snapshot_document_number varchar(40) not null,
    vehicle_snapshot_label varchar(200) not null,
    vehicle_snapshot_price numeric(19,2) not null,
    vehicle_snapshot_currency varchar(10) not null,
    calculated_at timestamp with time zone,
    constraint fk_loan_operations_user foreign key (user_id) references users (id),
    constraint fk_loan_operations_client foreign key (client_id) references clients (id),
    constraint fk_loan_operations_vehicle foreign key (vehicle_id) references vehicles (id)
);

create index idx_loan_operations_user_created_at on loan_operations (user_id, created_at desc);
create index idx_loan_operations_client on loan_operations (client_id);
create index idx_loan_operations_status on loan_operations (status);
create index idx_loan_operations_currency on loan_operations (operation_currency);

create table operation_charges (
    id bigint generated by default as identity primary key,
    operation_id bigint not null unique,
    desgravamen_rate numeric(19,4) not null,
    vehicle_insurance_rate numeric(19,4) not null,
    periodic_commission numeric(19,2) not null,
    postage_fee numeric(19,2) not null,
    administrative_fee numeric(19,2) not null,
    initial_charges numeric(19,2) not null,
    final_charges numeric(19,2) not null,
    constraint fk_operation_charges_operation foreign key (operation_id) references loan_operations (id) on delete cascade
);

create table operation_indicators (
    id bigint generated by default as identity primary key,
    operation_id bigint not null unique,
    financed_amount numeric(19,2),
    net_disbursement numeric(19,2),
    monthly_effective_rate numeric(19,6),
    base_installment numeric(19,2),
    total_interest numeric(19,2),
    total_amortization numeric(19,2),
    total_insurance numeric(19,2),
    total_charges numeric(19,2),
    total_payable numeric(19,2),
    npv numeric(19,2),
    irr_monthly numeric(19,6),
    irr_annual numeric(19,6),
    effective_annual_cost numeric(19,6),
    irr_converged boolean,
    calculation_version varchar(50),
    constraint fk_operation_indicators_operation foreign key (operation_id) references loan_operations (id) on delete cascade
);

create table operation_schedules (
    id bigint generated by default as identity primary key,
    operation_id bigint not null,
    installment_number integer not null,
    due_date date not null,
    opening_balance numeric(19,2),
    periodic_effective_rate numeric(19,6),
    grace_type_applied varchar(20),
    interest numeric(19,2),
    amortization numeric(19,2),
    base_installment numeric(19,2),
    insurance_amount numeric(19,2),
    charge_amount numeric(19,2),
    balloon_portion numeric(19,2),
    total_installment numeric(19,2),
    closing_balance numeric(19,2),
    debtor_cash_flow numeric(19,2),
    constraint fk_operation_schedules_operation foreign key (operation_id) references loan_operations (id) on delete cascade
);

create index idx_operation_schedules_operation on operation_schedules (operation_id, installment_number);

create table operation_audits (
    id bigint generated by default as identity primary key,
    operation_id bigint not null,
    action varchar(50) not null,
    description varchar(500) not null,
    user_id bigint not null,
    created_at timestamp with time zone not null,
    constraint fk_operation_audits_operation foreign key (operation_id) references loan_operations (id) on delete cascade,
    constraint fk_operation_audits_user foreign key (user_id) references users (id)
);

create index idx_operation_audits_operation_created_at on operation_audits (operation_id, created_at asc);
