alter table operation_schedules
    add column additional_charge_amount numeric(19,2);
alter table operation_schedules
    add column periodic_charges_amount numeric(19,2);

alter table operation_indicators
    add column initial_charges_financed numeric(19,2);
alter table operation_indicators
    add column initial_charges_paid_upfront numeric(19,2);
alter table operation_indicators
    add column initial_charges_withheld numeric(19,2);
alter table operation_indicators
    add column cash_at_signing numeric(19,2);
alter table operation_indicators
    add column total_additional_charges numeric(19,2);
alter table operation_indicators
    add column total_periodic_charges numeric(19,2);
alter table operation_indicators
    add column balloon_amount numeric(19,2);

create table operation_initial_charges (
    id bigint generated by default as identity primary key,
    operation_id bigint not null,
    code varchar(30) not null,
    label varchar(200) not null,
    amount numeric(19,2) not null,
    currency varchar(10) not null,
    financing_mode varchar(20) not null,
    taxable boolean not null,
    constraint fk_operation_initial_charges_operation foreign key (operation_id) references loan_operations (id) on delete cascade
);

create index idx_operation_initial_charges_operation on operation_initial_charges (operation_id);

create table operation_periodic_charges (
    id bigint generated by default as identity primary key,
    operation_id bigint not null,
    code varchar(30) not null,
    label varchar(200) not null,
    charge_type varchar(20) not null,
    amount numeric(19,2),
    currency varchar(10),
    rate_percent numeric(19,4),
    rate_base varchar(30),
    frequency varchar(30) not null,
    applies_during_grace boolean not null,
    from_installment integer not null,
    to_installment integer not null,
    constraint fk_operation_periodic_charges_operation foreign key (operation_id) references loan_operations (id) on delete cascade
);

create index idx_operation_periodic_charges_operation on operation_periodic_charges (operation_id);

create table operation_schedule_charge_breakdowns (
    id bigint generated by default as identity primary key,
    schedule_id bigint not null,
    code varchar(30) not null,
    label varchar(200) not null,
    amount numeric(19,2) not null,
    category varchar(30) not null,
    constraint fk_operation_schedule_charge_breakdowns_schedule foreign key (schedule_id) references operation_schedules (id) on delete cascade
);

create index idx_operation_schedule_charge_breakdowns_schedule on operation_schedule_charge_breakdowns (schedule_id);

create table public_quote_shares (
    id bigint generated by default as identity primary key,
    operation_id bigint not null,
    share_token varchar(80) not null unique,
    is_active boolean not null,
    expires_at timestamp with time zone,
    created_at timestamp with time zone not null,
    created_by_user_id bigint not null,
    constraint fk_public_quote_shares_operation foreign key (operation_id) references loan_operations (id) on delete cascade,
    constraint fk_public_quote_shares_user foreign key (created_by_user_id) references users (id)
);

create index idx_public_quote_shares_operation on public_quote_shares (operation_id);
